### ISSUE TITLE
Accept messages with NILVALUE ("-") in syslog header

### ISSUE THREAD

**Issue by petrkalina** [dcm4che-dockerfiles/logstash-dcm4chee#1]
The SYSLOG format allows NILVALUE (-) in some of the header fields. The https://tools.ietf.org/html/rfc5424#section-6 states:

     The syslog message has the following ABNF [RFC5234] definition:
      SYSLOG-MSG      = HEADER SP STRUCTURED-DATA [SP MSG]
      HEADER          = PRI VERSION SP TIMESTAMP SP HOSTNAME
                        SP APP-NAME SP PROCID SP MSGID

...

      TIMESTAMP       = NILVALUE / FULL-DATE "T" FULL-TIME
      HOSTNAME        = NILVALUE / 1*255PRINTUSASCII
      APP-NAME        = NILVALUE / 1*48PRINTUSASCII
      PROCID          = NILVALUE / 1*128PRINTUSASCII
      MSGID           = NILVALUE / 1*32PRINTUSASCII
      STRUCTURED-DATA = NILVALUE / 1*SD-ELEMENT

...

      NILVALUE        = "-"

The existing grok pattern for parsing syslog messages is:

    grok {
      match => { "message" => "<%{POSINT:syslog_pri}>1 %{TIMESTAMP_ISO8601:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program} %{POSINT:syslog_pid} %{DATA:syslog_msgid} - (\xEF\xBB\xBF)?%{GREEDYDATA:message}" }
      overwrite => [ "message" ]
    }

however, the neither of the used logstash patterns:

    %{TIMESTAMP_ISO8601}
    %{SYSLOGHOST}
    %{POSINT}

allow for this (see: https://github.com/logstash-plugins/logstash-patterns-core/blob/master/patterns/grok-patterns - in particular

    TIMESTAMP_ISO8601 %{YEAR}-%{MONTHNUM}-%{MONTHDAY}[T ]%{HOUR}:?%{MINUTE}(?::?%{SECOND})?%{ISO8601_TIMEZONE}?

    IPV6 ((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2})|:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1,3})|((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,4}){1,4})|((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-Fa-f]{1,4}){1,5})|((:[0-9A-Fa-f]{1,4}){0,3}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){1}(((:[0-9A-Fa-f]{1,4}){1,6})|((:[0-9A-Fa-f]{1,4}){0,4}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(:(((:[0-9A-Fa-f]{1,4}){1,7})|((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:)))(%.+)?
    IPV4 (?<![0-9])(?:(?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5])[.](?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5])[.](?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5])[.](?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5]))(?![0-9])
    IP (?:%{IPV6}|%{IPV4})
    HOSTNAME \b(?:[0-9A-Za-z][0-9A-Za-z-]{0,62})(?:\.(?:[0-9A-Za-z][0-9A-Za-z-]{0,62}))*(\.?|\b)
    IPORHOST (?:%{IP}|%{HOSTNAME})
    SYSLOGHOST %{IPORHOST}
    PROG [\x21-\x5a\x5c\x5e-\x7e]+
    SYSLOGPROG %{PROG:program}(?:\[%{POSINT:pid}\])?
    SYSLOGHOST %{IPORHOST}

    POSINT \b(?:[1-9][0-9]*)\b

Therefore, valid SYSLOG messages can be rejected.

Proposed solution: replace these patterns with %{NOTSPACE} pattern i.e.:

    grok {
      match => { "message" => "<%{POSINT:syslog_pri}>1 %{TIMESTAMP_ISO8601:syslog_timestamp} %{NOTSPACE:syslog_hostname} %{NOTSPACE:syslog_program} %{NOTSPACE:syslog_pid} %{NOTSPACE:syslog_msgid} - (\xEF\xBB\xBF)?%{GREEDYDATA:message}" }
      overwrite => [ "message" ]
    }

note that this still retains the requirement for a valid timestamp as this is required for the valid parsing of this field and correct indexing in elasticsearch.

**Comment by gunterze** [comment]
Fixed by 5c1bb0f4f5a2a0255713e357c51a230ac2d645b7
